# Note: GitHub Actions only triggers on YAML files in .github/workflows/
# pr-view.py is just a script, it must be called from a workflow .yml file (not placed here directly)


name: PR Reviewer Bot

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write   #  allow posting PR comments

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests groq

      - name: Run PR reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # works if PR is from same repo
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}         # optional fallback if PRs come from forks
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python review_bot.py
give discription that how this code is help in automation
